/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package casting.java;

import models.Felino;
import models.Gato;

public class App {
    public static void main(String[] args) {

        Felino f = new Felino();
        f.setName("Felino felix");
        f.comer(); // comendo.
        Gato g = new Gato("Tom", "Vira-lata");
        g.comer(); // comendo ração.
        g.ronronar();

        // upcasting
        System.out.println("== Felino f2 upcasting");
        Felino f2 = new Gato();
        f2.setName("Catatau");
        f2.comer();

        // downcasting
        System.out.println("== Gato g2 downcasting");
        Gato g2 = (Gato)f2;
        g2.getName();
        g2.comer();
        g2.ronronar();

        // System.out.println(f);
        // System.out.println(f2);
        // System.out.println(g);
        // System.out.println(g2);
    }
}
